name: Install WP-CLI
description: >-
  Install WP-CLI utility in your GitHub workflow.
author: holyhope
branding:
  icon: terminal
  color: blue
inputs:
  version:
    description: >-
      [Version of WP-CLI](https://github.com/wp-cli/wp-cli/releases) to install.

      Default: `latest` version
    required: false
  verify:
    description: >-
      True to check the WP-CLI binary's integrity and authenticity.
      False to skip the checks.
    required: false
    default: 'true'

outputs:
  path:
    description: Path to the WP-CLI binary.
    value: ${{ steps.wp_cli_install.outputs.path }}

runs:
  using: composite
  steps:
    - name: Prepare wp-cli installation
      id: wp_cli_prepare
      shell: bash
      run: >-
        echo "installation_dir=$( \
          mktemp -d \
            --tmpdir='${{ runner.temp }}' \
            'wp-cli.XXXXXX')" \
          >> "$GITHUB_OUTPUT"

    - uses: robinraju/release-downloader@v1.9
      id: wp_cli
      with:
        repository: wp-cli/wp-cli
        tag: ${{ inputs.version && inputs.version || '' }}
        latest: ${{ ! inputs.version }}
        out-file-path: '${{ steps.wp_cli_prepare.outputs.installation_dir }}'
        fileName: >-
          ${{ ! inputs.verify
            && 'wp-cli-*.phar'
            || '*' }}

    - name: wp-cli installation
      id: wp_cli_install
      shell: bash
      run: |-
        WP_CLI_BINARY=$( \
          find '${{ steps.wp_cli_prepare.outputs.installation_dir }}' \
            -name '*.phar' -type f)

        if [[ -z "$WP_CLI_BINARY" ]] ; then
          echo 'No binary found' >&2
          exit 1
        fi

        if [[ $(wc -l <<< "$WP_CLI_BINARY") -gt 1 ]] ; then
          echo 'Multiple binaries found' >&2
          exit 1
        fi

        chmod +x "$WP_CLI_BINARY"
        cat <<EOF >> "$GITHUB_OUTPUT"
        path=$WP_CLI_BINARY
        signature_file=$WP_CLI_BINARY.asc
        sha256_file=$WP_CLI_BINARY.sha256
        EOF

    - name: Verify wp-cli binary
      if: ${{ inputs.verify }}
      shell: bash
      run: |-
        echo '::group::Verify WP-CLI binary'

        WP_CLI_KEY="$(mktemp --tmpdir='${{ runner.temp }}' 'XXXXXX.key')"
        KEYRING="$(mktemp --tmpdir='${{ runner.temp }}' 'XXXXXX.gpg')"

        # https://github.com/wp-cli/builds?tab=readme-ov-file#wp-cli-builds
        cat <<EOF > "$WP_CLI_KEY"
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mQENBFsQEBkBCADfGAhxQ71XaIk31SjD8dNH3uVNtPh/2SIIhYbObMvEG6uoMucP
        t3jCsnkh/veKBkJ+HJ/XcARGoFYdaCZo5PTORBWOwHmeWPbu7aiAM4v3EKPc8wZP
        jabtEejwZrRFlSlAu5YL25ldz5KNgvGOBdje9jUi2iovQ4lfjMEuH2sXhmDQPbDW
        22Fb2xinvmlnyf5kJn9ADiWm6VEnaNvaL96TCC1iUrMJmYI0m29j2sVbKJIq8ZBO
        CgtY4llPC7QskWw8VXEAq2WnQeZMVLqxOSoRDy/qUvw0RR+DfiXsrHjBxAH4uvHK
        zUdnMl1Qbh2A/rfcsIaJubXg5pUXwF7TCvSPABEBAAG0JVdQLUNMSSBSZWxlYXNl
        cyA8cmVsZWFzZXNAd3AtY2xpLm9yZz6JAU4EEwEIADgCGwMFCwkIBwIGFQgJCgsC
        BBYCAwECHgECF4AWIQRjr3qhUGfAVhb93YijoujyJvC8BgUCWxAQ7AAKCRCjoujy
        JvC8BmYTCACPEYQr89U/H/iQcI012UaOSLYLx+Qj9oA7p9gv2mZSBHNSijzhnizo
        QBEg7q7BXF8B8UqL9ZhUWfG9PiR8kkFbBN1sIY0RM5cFltb3cJthVH4ZV8SUiGW6
        zIOd8m5JXVnekmZyJFpufxDHms6F3Z2RNUbdZSp2Mj+5p/a4GtJhfGGpfYBbXOxG
        gdx5dmipjlxfP5M3YL4QCJoySB+sY92de5b3S3tqmj7ldb/GRvN/7XjoMDwbRso6
        jrhGtk8TjtAV0l/VdjebpI6zivrDLYDQq5vwi6hGPl7k88ElU47vaJiJX5yXaJ/k
        LFQ3g8raFQq69nqcDjJLGds+Y+lAXrtzuQENBFsQEBkBCAC9ZUHiXbBLvCejMXKK
        vFpKaVsovI6RBU8l0sC+00yvpP+TJmRXracnesTqHyTlhAUMhpbFvG0mBMBdROt5
        IPRZ2S9JdJKZFVqO7Nop0elO8wUe6rsEHisUbEP49BcqDHGxfEnB/MubnJO1hHEH
        1ftnZBEQW3jNagOTikki9675qF4ONvaSeCY9DkHa4lbau24SzePvtWuxYGsdX+Jf
        ikFxq8N2ArPlSoVv/DKEbl5dgz1hYFJ9qBKoXSbaKk1TxZ4bA8nxcznZHS+8Lirv
        tEjB8Z68Hz+pXIFJBbchC/FMatZC2hjFobedc4dT3nxf5iiH9XsHI5bqp3UEsPlx
        8LP5ABEBAAGJATYEGAEIACACGwwWIQRjr3qhUGfAVhb93YijoujyJvC8BgUCWxAR
        IQAKCRCjoujyJvC8BhGMCACkNhkshrOYDRoOwny8m1mI2nSIU0KnjEruaeAXrY2T
        5VHNfLkTX3wD2HYO97r1CvUNBUWpmTwSicK0Z6TCDp4A9Oi+z5CA/5zBT/iydC6E
        czNAPUehdLKka9Qs0vrVq22S0dDiA4xXZUvQpoo8VUKlvau9igF98mbd56U89s3L
        gg7O72A/4x7rhDO0Q+U8SIBJtFmEHIcu6gHkooQW3d7opHKCjbnyqxDQ/iUY3b8o
        n75TXnDJWbjCFTiTMyVTeyQfK0Us8FbJNXhMMagalRQu/sBH56S7Cg2OLciQB1B2
        sLbhbfYDXYriI/OGVIPvCEIH6FX4+KiFy7RS+0JthI0R
        =fQDM
        -----END PGP PUBLIC KEY BLOCK-----
        EOF

        gpg --yes -o "$KEYRING" --dearmor "$WP_CLI_KEY"
        rm -f "$WP_CLI_KEY"

        gpg \
          --status-fd 1 \
          --no-default-keyring \
          --keyring "$KEYRING" \
          --trust-model always \
          --verify \
          '${{ steps.wp_cli_install.outputs.signature_file }}'
        rm -f "$KEYRING"

        (
          cat '${{ steps.wp_cli_install.outputs.sha256_file }}' \
            | tr '\n' ' ' ;
          ls '${{ steps.wp_cli_install.outputs.path }}' \
        ) | sha256sum --check || (
          echo 'SHA-256 verification failed' >&2 ;
          exit 1
        )

        echo '::endgroup::'
